# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LabelPageTurning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LabelPageTurning
  pod 'ButtersCode', :path=>'../ButtersCode'
  pod 'YYKit', '~> 1.0.9'
#  pod 'MJRefresh', '~> 3.7.5'
end
